/**
 * Campaign Interface
 *
 * This interface defines the structure of a campaign object used throughout the application.
 * It contains all the properties needed to represent a marketing campaign.
 */
export interface Campaign {
  id: string       // Unique identifier for the campaign
  name: string     // Name/title of the campaign
  startDate: string // Start date of the campaign (stored as string)
  endDate: string  // End date of the campaign (stored as string)
  clicks: number   // Number of clicks the campaign has received
  cost: number     // Total cost spent on the campaign
  revenue: number  // Total revenue generated by the campaign
  profit?: number  // Calculated field (revenue - cost), optional as it may be calculated on demand
}
